import type { Project } from './types'

export const dummyProjects: Project[] = [
  {
    id: 'proj-1',
    name: 'Copper Ridge Exploration',
    location: 'Nevada, USA',
    date: '2024-03-15',
    status: 'active',
    description: 'Reconnaissance survey for porphyry copper indicators in the Great Basin region. Focus on alteration halos and secondary copper minerals.',
    createdAt: '2024-03-15T08:00:00Z',
    samples: [
      {
        id: 'sample-1',
        projectId: 'proj-1',
        sampleNumber: 'CR-001',
        sampleName: 'Quartz Vein Sample A',
        coordinates: { latitude: 39.5296, longitude: -119.8138 },
        rockCategory: 'Igneous Rocks',
        rockSubcategory: 'Plutonic (Intrusive)',
        rockName: 'Granodiorite',
        rockType: 'Intrusive',
        grainSize: 'medium',
        color: 'gray',
        weathering: 'w2',
        mineralization: 'quartz-veins-sulfides',
        alterationType: 'phyllic',
        alterationIntensity: 3,
        hardness: 6,
        structuralFeature: 'vein',
        strike: 45,
        dip: 60,
        dipDirection: 'NE',
        structuralNotes: 'Quartz vein with pyrite and chalcopyrite, hosted in altered granodiorite.',
        photos: [],
        fieldNotes: 'Strong silicification along vein margins. Secondary malachite staining visible on surface exposures. Sample collected for assay.',
        voiceRecordings: [],
        createdAt: '2024-03-15T09:30:00Z'
      },
      {
        id: 'sample-2',
        projectId: 'proj-1',
        sampleNumber: 'CR-002',
        sampleName: 'Oxide Zone Sample',
        coordinates: { latitude: 39.5301, longitude: -119.8142 },
        rockCategory: 'Hybrid / Special Rock Systems',
        rockSubcategory: 'Ore-bearing',
        rockName: 'Gossan',
        rockType: 'Weathered',
        grainSize: 'fine',
        color: 'gossanous-red-brown',
        weathering: 'w4',
        mineralization: 'gossan',
        alterationType: 'limonitization',
        alterationIntensity: 4,
        hardness: 4,
        structuralFeature: 'contact',
        strike: 50,
        dip: 70,
        dipDirection: 'NE',
        structuralNotes: 'Contact between altered intrusive and sedimentary rocks.',
        photos: [],
        fieldNotes: 'Intensely weathered gossan cap with boxwork textures. Limonite and goethite dominant. Possible supergene copper below.',
        voiceRecordings: [],
        createdAt: '2024-03-15T11:00:00Z'
      }
    ]
  },
  {
    id: 'proj-2',
    name: 'Gold Coast Mapping',
    location: 'Queensland, Australia',
    date: '2024-02-20',
    status: 'complete',
    description: 'Regional geological mapping project focused on greenstone belt sequences and gold-bearing structures.',
    createdAt: '2024-02-20T08:00:00Z',
    samples: [
      {
        id: 'sample-3',
        projectId: 'proj-2',
        sampleNumber: 'GC-001',
        sampleName: 'Banded Iron Formation',
        coordinates: { latitude: -23.4234, longitude: 150.5172 },
        rockCategory: 'Sedimentary Rocks',
        rockSubcategory: 'Chemical',
        rockName: 'Banded Iron Formation (BIF)',
        rockType: 'Chemical Sedimentary',
        grainSize: 'very-fine',
        color: 'dark-gray',
        weathering: 'w1',
        mineralization: 'banded',
        alterationType: 'silicification',
        alterationIntensity: 2,
        hardness: 7,
        structuralFeature: 'bedding',
        strike: 270,
        dip: 45,
        dipDirection: 'W',
        structuralNotes: 'Well-preserved bedding in BIF sequence, folded.',
        photos: [],
        fieldNotes: 'Alternating magnetite and chert bands, 2-5mm thick. Minor sulfide mineralization in fold hinges.',
        voiceRecordings: [],
        createdAt: '2024-02-20T10:00:00Z'
      },
      {
        id: 'sample-4',
        projectId: 'proj-2',
        sampleNumber: 'GC-002',
        sampleName: 'Auriferous Quartz Vein',
        coordinates: { latitude: -23.4256, longitude: 150.5198 },
        rockCategory: 'Metamorphic Rocks',
        rockSubcategory: 'Non-foliated',
        rockName: 'Quartzite',
        rockType: 'Metamorphic',
        grainSize: 'medium',
        color: 'white',
        weathering: 'w1',
        mineralization: 'gold',
        alterationType: 'silicification',
        alterationIntensity: 5,
        hardness: 7,
        structuralFeature: 'vein',
        strike: 315,
        dip: 80,
        dipDirection: 'NW',
        structuralNotes: 'Steep quartz vein cutting through greenstone.',
        photos: [],
        fieldNotes: 'Massive white quartz with visible gold specks. Arsenopyrite and pyrite present. High-grade sample.',
        voiceRecordings: [],
        createdAt: '2024-02-20T14:30:00Z'
      }
    ]
  },
  {
    id: 'proj-3',
    name: 'Alpine Metamorphics Study',
    location: 'Valais, Switzerland',
    date: '2024-01-10',
    status: 'draft',
    description: 'Academic research project studying high-pressure metamorphic assemblages in the Pennine Alps.',
    createdAt: '2024-01-10T08:00:00Z',
    samples: [
      {
        id: 'sample-5',
        projectId: 'proj-3',
        sampleNumber: 'AM-001',
        sampleName: 'Eclogite Sample',
        coordinates: { latitude: 45.9838, longitude: 7.7656 },
        rockCategory: 'Metamorphic Rocks',
        rockSubcategory: 'Non-foliated',
        rockName: 'Eclogite',
        rockType: 'High-P Metamorphic',
        grainSize: 'coarse',
        color: 'green',
        weathering: 'w1',
        mineralization: 'none',
        alterationType: 'none',
        alterationIntensity: 0,
        hardness: 6,
        structuralFeature: 'foliation',
        strike: 180,
        dip: 30,
        dipDirection: 'S',
        structuralNotes: 'Weak foliation defined by omphacite alignment.',
        photos: [],
        fieldNotes: 'Fresh eclogite with garnet porphyroblasts up to 2cm diameter. Omphacite-rich matrix. Possible UHP indicators.',
        voiceRecordings: [],
        createdAt: '2024-01-10T11:00:00Z'
      }
    ]
  },
  {
    id: 'proj-4',
    name: 'Volcanic Hazard Assessment',
    location: 'Kamchatka, Russia',
    date: '2024-04-01',
    status: 'active',
    description: 'Monitoring and sampling program for active volcanic systems. Focus on recent pyroclastic deposits.',
    createdAt: '2024-04-01T08:00:00Z',
    samples: [
      {
        id: 'sample-6',
        projectId: 'proj-4',
        sampleNumber: 'VH-001',
        sampleName: 'Recent Pumice Fall',
        coordinates: { latitude: 53.2567, longitude: 158.8342 },
        rockCategory: 'Igneous Rocks',
        rockSubcategory: 'Volcanic (Extrusive)',
        rockName: 'Pumice',
        rockType: 'Volcanic',
        grainSize: 'vesicular',
        color: 'light-gray',
        weathering: 'w1',
        mineralization: 'none',
        alterationType: 'none',
        alterationIntensity: 0,
        hardness: 5,
        structuralFeature: 'bedding',
        strike: 0,
        dip: 5,
        dipDirection: 'N',
        structuralNotes: 'Horizontal bedding in pumice fall deposit.',
        photos: [],
        fieldNotes: 'White to light gray pumice clasts, 1-5cm diameter. Highly vesicular, floats on water. Dated to 2023 eruption.',
        voiceRecordings: [],
        createdAt: '2024-04-01T09:00:00Z'
      },
      {
        id: 'sample-7',
        projectId: 'proj-4',
        sampleNumber: 'VH-002',
        sampleName: 'Andesite Lava Flow',
        coordinates: { latitude: 53.2589, longitude: 158.8367 },
        rockCategory: 'Igneous Rocks',
        rockSubcategory: 'Volcanic (Extrusive)',
        rockName: 'Andesite',
        rockType: 'Volcanic',
        grainSize: 'porphyritic',
        color: 'dark-gray',
        weathering: 'w1',
        mineralization: 'none',
        alterationType: 'none',
        alterationIntensity: 0,
        hardness: 6,
        structuralFeature: 'contact',
        strike: 90,
        dip: 15,
        dipDirection: 'E',
        structuralNotes: 'Base of lava flow showing flow banding.',
        photos: [],
        fieldNotes: 'Porphyritic andesite with plagioclase and pyroxene phenocrysts. Flow-banded texture near base. Part of 2022 eruption sequence.',
        voiceRecordings: [],
        createdAt: '2024-04-01T14:00:00Z'
      }
    ]
  }
]
